branch-defaults:
  default:
    environment: arboretum-dev
global:
  application_name: arboretum
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
